### ISSUE TITLE
Add support for other languages in metadata protocol

### ISSUE THREAD

**Issue by zheli** [lbryio/lbryschema#8]
Add support for other languages in:

https://github.com/lbryio/lbryschema/blob/master/lbryschema/proto/metadata.proto

Right now if I try to publish a file with languages other than English, I will get an exception:

> 2017-05-25 10:30:56,828 ERROR    lbrynet.lbrynet_daemon.auth.server:346: Failed to process publish: Failed to parse language field: Invalid enum value zh for enum type Metadata.Language.
> Traceback (most recent call last):
>   File "site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
>   File "site-packages/lbrynet/core/Wallet.py", line 909, in claim_name
>   File "site-packages/lbryschema/claim.py", line 140, in load_dict
>   File "site-packages/lbryschema/claim.py", line 34, in protobuf
>   File "site-packages/lbryschema/schema/claim.py", line 33, in load
>   File "site-packages/lbryschema/schema/stream.py", line 14, in load
>   File "site-packages/lbryschema/schema/metadata.py", line 17, in load
>   File "site-packages/lbryschema/schema/schema.py", line 15, in _load
>   File "site-packages/google/protobuf/json_format.py", line 369, in Parse
>   File "site-packages/google/protobuf/json_format.py", line 384, in ParseDict
>   File "site-packages/google/protobuf/json_format.py", line 415, in ConvertMessage
>   File "site-packages/google/protobuf/json_format.py", line 501, in _ConvertFieldValuePair
> ParseError: Failed to parse language field: Invalid enum value zh for enum type Metadata.Language.

**Comment by atiger7758** [comment]
应该不支持吧

**Comment by kauffj** [comment]
@jackrobison any reason other language codes can't at least be considered valid metadata?

**Comment by jackrobison** [comment]
@kauffj 

Nope, add away!

**Comment by jackrobison** [comment]
Fixed in https://github.com/lbryio/lbryschema/pull/14
